# Generated by Django 6.0.3 on 2026-04-02 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="update_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
