# Generated by Django 6.0.3 on 2026-04-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_character"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="background_img",
            new_name="background_image",
        ),
    ]
