# Generated by Django 6.0.3 on 2026-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_message_input"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="output",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="message",
            name="user_message",
            field=models.TextField(max_length=500),
        ),
    ]
